
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS ID TIMESS : L EQUALS RS : RL : TIMES RL : IDR : L'
    
_lr_action_items = {'TIMES':([0,4,6,],[4,4,4,]),'ID':([0,4,6,],[5,5,5,]),'$end':([1,2,3,5,7,8,9,],[0,-5,-2,-4,-3,-5,-1,]),'EQUALS':([2,5,7,8,],[6,-4,-3,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'L':([0,4,6,],[2,8,8,]),'R':([0,4,6,],[3,7,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> L EQUALS R','S',3,'p_P0','slrvslalr.py',11),
  ('S -> R','S',1,'p_P1','slrvslalr.py',14),
  ('L -> TIMES R','L',2,'p_P2','slrvslalr.py',17),
  ('L -> ID','L',1,'p_P3','slrvslalr.py',20),
  ('R -> L','R',1,'p_P4','slrvslalr.py',23),
]
